name: uidesigntocode_2
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

enviroment:
  sdk: ^3.5.3

dependencies: 
  flutter:
    sdk: flutter


  curpertino_icons: ^1.0.8
  dotted_line: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/